version:  '3.7'
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - '../:/usr/src/app'
        user: ${LOCAL_USER}
        networks:
            - api_ex_shared_mysql
    auth_nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - '../public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - php
        networks:
            - api_ex_shared_mysql

volumes:
    db_data:

networks:
    api_ex_shared_mysql:
        external: true
