version:  '3.7'
services:
    mysql:
        image: mysql:5.6
        restart: on-failure
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
        volumes:
            - db_data:/var/lib/mysql:rw
        ports:
            - '${MYSQL_PORT}:3306'
        networks:
            - shared_mysql
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - '../:/usr/src/app'
        user: ${LOCAL_USER}
        networks:
            - shared_mysql
    api_nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - '../public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - php
        networks:
            - shared_mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: on-failure
        ports:
            - '${PHPMYADMIN_PORT}:80'
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: ${MYSQL_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - php
            - mysql
        networks:
            - shared_mysql

volumes:
    db_data:

networks:
    shared_mysql:
